// ============================================================
// ADC Wrapper — MAX 10 Internal ADC, Channel 0 (Arduino A0)
// ============================================================
// The MAX 10 ADC is accessed through a Quartus Platform Designer
// (Qsys) IP core called "MAX 10 ADC".  Because the IP is
// generated by Quartus (not hand-coded), this file shows you
// exactly how to generate it and then wraps the resulting
// instantiation in a clean interface.
//
// ── HOW TO GENERATE THE ADC IP ──────────────────────────────
//
//  1. Open your project in Quartus Prime (Lite Edition ≥ 17.1).
//
//  2. Go to  Tools → Platform Designer  (or IP Catalog).
//
//  3. In the IP Catalog search for  "MAX 10 ADC".
//     Double-click it to open the parameter editor.
//
//  4. Set the following options:
//       • ADC clock source  : Dedicated ADC clock (or use FPGA
//                             fabric clock if unavailable)
//       • ADC clock freq.   : 5 MHz  (max for MAX 10 ADC)
//       • Prescaler         : Divides your 50 MHz → 5 MHz
//                             → set prescaler = 10
//       • Number of channels: 1  (only need Channel 0 = A0)
//       • Channel 0 input   : SINGLE_ENDED
//       • Resolution        : 12 bit
//
//  5. Click  "Generate HDL…"  and save the resulting IP files
//     inside  fpga/ip/max10_adc/  (the .qip will be added
//     automatically when you add it to the project).
//
//  6. Add the generated .qip file to your Quartus project:
//       Project → Add/Remove Files → browse to
//       fpga/ip/max10_adc/max10_adc.qip
//
//  7. Replace the SIMULATION STUB section below with the real
//     instantiation (copy the template from the generated
//     max10_adc_inst.v example file).
//
// ── PIN NOTE ────────────────────────────────────────────────
// Arduino A0 maps to  ADCIN1  on the DE10-Lite board.
// The DE10-Lite User Manual (Table 3-8) lists:
//     ADCIN1 → FPGA ball F6
// No .qsf pin assignment is needed for analogue inputs; the
// ADC IP connects directly inside the device fabric.
//
// ── SIMULATION STUB (replace with real IP instance) ─────────
// During simulation / before IP generation, this stub generates
// a sawtooth ramp so you can verify the display logic without
// real hardware.
// ============================================================

module adc_wrapper (
    input        clk,       // 50 MHz system clock
    input        rst_n,     // active-low reset
    output reg [11:0] adc_raw,    // 12-bit ADC result (0..4095)
    output reg        adc_valid   // 1-cycle pulse: new sample ready
);

`ifdef SIMULATION
    // ── Simulation stub: ramp 0 → 4095 in ~4 ms steps ──────
    reg [25:0] sim_cnt;
    reg [11:0] sim_ramp;

    localparam SIM_PERIOD = 26'd200_000;  // ~4 ms at 50 MHz

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sim_cnt   <= 26'd0;
            sim_ramp  <= 12'd0;
            adc_raw   <= 12'd0;
            adc_valid <= 1'b0;
        end else begin
            adc_valid <= 1'b0;
            if (sim_cnt == SIM_PERIOD - 1) begin
                sim_cnt   <= 26'd0;
                sim_ramp  <= sim_ramp + 12'd41;   // ~3300/80 steps ≈ 41
                adc_raw   <= sim_ramp;
                adc_valid <= 1'b1;
            end else begin
                sim_cnt <= sim_cnt + 1;
            end
        end
    end

`else
    // ── Real hardware: instantiate Quartus-generated ADC IP ──
    //
    // TODO: Replace this block with the actual IP instantiation.
    //
    // After generating the IP in Platform Designer, the
    // instantiation template will look approximately like this
    // (exact port names depend on your Quartus version):
    //
    //   max10_adc u_max10_adc (
    //       .clock          (clk),
    //       .reset_n        (rst_n),
    //       .ch1_data       (adc_raw),      // channel 1 = A0
    //       .ch1_data_valid (adc_valid),
    //       // other channels left unconnected
    //   );
    //
    // Until you generate the IP, this module will hold adc_raw=0
    // and never pulse adc_valid (the display will read 0.00 V).

    // Placeholder — synthesises to all-zero; safe default
    initial begin
        adc_raw   = 12'd0;
        adc_valid = 1'b0;
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            adc_raw   <= 12'd0;
            adc_valid <= 1'b0;
        end
        // Real assignment comes from IP instance above.
        // TODO: remove this always block once IP is instantiated.
    end

`endif

endmodule
